---
- group: name=ingester system=yes
- user: name=ingester system=yes group=ingester

- name: Install jre
  apt:
    name: openjdk-8-jre
    update_cache: yes

- name: Create ingester lib directories
  file:
    path: /usr/lib/ingester
    state: directory

- name: Create ingester working directories
  file:
    path: /var/ingester
    state: directory
    owner: "ingester"
    group: "ingester"

- name: Download ingester
  copy:
    src: "perftest.jar"
    dest: "/usr/lib/ingester/perftest.jar"
  notify: Restart ingesters

- name: Add systemd services
  template:
    src: "ingester@.service.j2"
    dest: "/etc/systemd/system/ingester@.service"
  notify: Restart ingesters

- service:
    name: "ingester@{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_sequence: count={{ ingest_instances }}