zookeeper_version: 3.4.13
zookeeper_url: "http://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
zookeeper_host: localhost
zookeeper_port: 2181
zookeeper_id: 1

kafka_log_dirs: "/var/humio/kafka/data"

humio_java_opts_Xmx: 84G
humio_java_opts:
  - "-server"
  - "-XX:+UseParallelOldGC"
  - "-Xms{{ humio_java_opts_Xms }}"
  - "-Xmx{{ humio_java_opts_Xmx }}"
  - "-Xss{{ humio_java_opts_Xss }}"
  - "-Xlog:gc*,gc+jni=debug:file=${HUMIO_DEBUGLOG_DIR}/gc_humio.log:time,tags:filecount=5,filesize=102400"
  - "-Dhumio.auditlog.dir=${HUMIO_AUDITLOG_DIR}"
  - "-Dhumio.debuglog.dir=${HUMIO_DEBUGLOG_DIR}"

output_conf:
  "elasticsearch":
    "hosts": ["{{ lookup('env', 'HUMIO_PARENT_URL') }}"]
    "username": "{{ lookup('env', 'HUMIO_PARENT_INGEST_TOKEN') }}"

beats_version: 6.6.0

humio_disks:
  - description: "Humio primary disk"
    disk: "/dev/md/primary"
    destination: "/var/humio/primary"
    type: "xfs"
  - description: "Humio secondary disk"
    disk: "/dev/md/secondary"
    destination: "/var/humio/secondary"
    type: "xfs"
