---
- hosts: all
  become: true
  serial: 10
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      tags: always
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
  roles:
  - role: ansible-beats
    tags: monitoring
    beat: "metricbeat"
    beat_conf:
      "metricbeat.modules":
      - "module": "system"
        "metricsets":
          - "cpu"
          - "load"
          - "core"
          - "diskio"
          - "filesystem"
          - "fsstat"
          - "memory"
          - "network"
          - "process"
          - "socket"
        "enabled": true
        "period": "10s"
        "processes": [".*"]
        "cpu_ticks": false
      fields:
        "@tags": ["@host"]

- hosts:
    - tag_kafkas
    - tag_humios
  tags: disk
  become: true
  tasks:
    - name: create mount targets
      file:
        path: "{{ item.destination }}"
        state: directory
      loop: "{{ humio_disks }}"
    - name: Systemd mount config
      copy:
        content: |
          [Unit]
          Description={{ item.description }}

          [Mount]
          What={{ item.disk }}
          Where={{ item.destination }}
          Type={{ item.type }}
          Options=defaults

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/{{ item.destination | replace('/', '', 1) | replace('/', '-') }}.mount"
      loop: "{{ humio_disks }}"
    - name: Start mount
      service:
        name: "{{ item.destination | replace('/', '', 1) | replace('/', '-') }}.mount"
        enabled: true
        daemon_reload: true
        state: started
      loop: "{{ humio_disks }}"
    - name: Update facts
      setup:

- hosts: tag_zookeepers
  tags: zookeeper
  become: true
  roles:
    - role: humio.java
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['tag_zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['ansible_local']['cluster_index'], host=host, ip=hostvars[host]['ansible_bond0_0'].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"

- hosts: tag_kafkas
  tags: kafka
  serial: 1
  become: true
  roles:
    - role: humio.java
    - role: humio.kafka
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['tag_zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['ansible_local']['cluster_index'], host=host, ip=hostvars[host]['ansible_bond0_0'].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      kafka_broker_id: "{{ ansible_local['cluster_index'] }}"
      kafka_listeners:
        - host: "{{ ansible_bond0_0.ipv4.address }}"

- hosts: tag_humios
#  tags: humio
  serial: 1
  become: true
  roles:
    - role: "ansible-beats"
      beat: "filebeat"
      beat_conf:
        "filebeat":
          "inputs":
            - paths:
              - /var/log/syslog
              - /var/log/auth.log
              fields:
                "@type": syslog-utc
                "@tags": ["@host", "@type"]
            - paths:
              - /var/log/humio/*/humio-debug.log
              fields:
                "@type": humio
                "@tags": ["@host", "@type"]
              multiline:
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                negate: true
                match: after
            - paths:
              - /var/log/kafka/server.log
              fields:
                "@type": kafka
                "@tags": ["@host", "@type"]
              multiline:
                pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
                negate: true
                match: after
    - role: entercloudsuite.haproxy
      haproxy_conf: |
        listen web
          mode http
          bind *:80
          server humio-0 127.0.0.1:8080 maxconn 64
          server humio-1 127.0.0.1:8081 maxconn 64

    - role: humio.java
    - role: humio.server
      tags: humio
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['tag_zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['ansible_local']['cluster_index'], host=host, ip=hostvars[host]['ansible_bond0_0'].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      kafka_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['tag_kafkas'] %}
       {{- ips.append(dict(id=hostvars[host]['ansible_local']['cluster_index'], host=host, ip=hostvars[host]['ansible_bond0_0'].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      humio_host_id: "{{ ansible_local['cluster_index'] }}"
      humio_data_path: "/var/humio/primary"
      humio_data_secondary_path: "/var/humio/secondary"
      humio_config:
        "0": |
          EXTERNAL_URL=http://{{ ansible_bond0_0.ipv4.address }}:8080
        "1": |
          EXTERNAL_URL=http://{{ ansible_bond0_0.ipv4.address }}:8081

- hosts: localhost
  connection: local
  tasks:
    - name: Rebalance partitions
      tags: humio
      uri:
        url: "http://{{ hostvars[groups['tag_humios']|random]['ansible_bond0'].ipv4.address }}:8080/api/v1/clusterconfig/partitions/setdefaults"
        method: POST
    - debug:
        msg: "Congratulations. Humio is now available at http://{{ hostvars[groups['tag_humios']|random]['ansible_bond0'].ipv4.address }}:8080"
