---
############################################
#
# Install Metricbeat on all hosts
#
- hosts: all
  tags: always
  roles:
  - role: ansible-beats
    become: true
    beat: "metricbeat"
    beat_conf:
      "metricbeat.modules":
      - "module": "system"
        "metricsets":
          - "cpu"
          - "load"
          - "core"
          - "diskio"
          - "filesystem"
          - "fsstat"
          - "memory"
          - "network"
          - "process"
          - "socket"
        "enabled": true
        "period": "10s"
        "processes": [".*"]
        "cpu_ticks": false


############################################
#
# Install Java + Zookeeper roles on zookeeper hosts
#
- hosts: zookeepers
  tags: zookeeper
  become: true
  roles:
    - role: humio.java
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"

############################################
#
# Install Java + Kafka roles on kafka hosts
#
- hosts: kafkas
  tags: kafka
  serial: 1
  become: true
  roles:
    - role: humio.java
    - role: humio.kafka
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      kafka_broker_id: "{{ cluster_index }}"
      kafka_listeners:
        - host: "{{ hostvars[inventory_hostname]['ansible_' + humio_network_interface].ipv4.address }}"

############################################
#
# Install Filebeat + HAProxy + Java + Humio roles on humio hosts
#
- hosts: humios
  tags: humio
  serial: 1
  become: true
  roles:
    - role: ansible-beats
      beat: "filebeat"
      beat_conf:
        "filebeat":
          "inputs":
            - paths:
              - /var/log/syslog
              - /var/log/auth.log
              fields:
                "@type": syslog-utc
                "@tags": ["@host", "@type"]
            - paths:
              - /var/log/humio/*/humio-debug.log
              fields:
                "@type": humio
                "@tags": ["@host", "@type"]
              multiline:
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                negate: true
                match: after
            - paths:
              - /var/log/kafka/server.log
              fields:
                "@type": kafka
                "@tags": ["@host", "@type"]
              multiline:
                pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
                negate: true
                match: after
    - role: entercloudsuite.haproxy
      haproxy_conf: |
        listen web
          mode http
          bind *:80
          server humio-0 127.0.0.1:8080 maxconn 64
          server humio-1 127.0.0.1:8081 maxconn 64

    - role: humio.java
    - role: humio.server
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      kafka_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['kafkas'] %}
       {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host]['ansible_' + humio_network_interface].ipv4.address)) }}
       {%- endfor %}
       {{- ips -}}"
      humio_host_id: "{{ cluster_index }}"
      humio_config:
        "0": "EXTERNAL_URL=http://{{ hostvars[inventory_hostname]['ansible_' + humio_network_interface].ipv4.address }}:8080"
        "1": "EXTERNAL_URL=http://{{ hostvars[inventory_hostname]['ansible_' + humio_network_interface].ipv4.address }}:8081"

############################################
#
# Execute Humio API requests to the Cluster Management API
# to rebalance the Humio storage and digest partitions
# https://docs.humio.com/api/cluster-management-api/
#
- hosts: localhost
  connection: local
  tasks:
    - name: Rebalance partitions
      tags: humio
      uri:
        url: "http://{{ hostvars[groups['humios']|random]['ansible_' + humio_network_interface].ipv4.address }}:8080/api/v1/clusterconfig/partitions/setdefaults"
        method: POST
    - name: Create repository
      tags: humio
      uri:
        url: "http://{{ hostvars[groups['humios']|random]['ansible_' + humio_network_interface].ipv4.address }}:8080/graphql"
        method: POST
        body_format: json
        body: |
          {
            "query":"mutation {createRepository(name: \"dataspace0\") {__typename}}"
          }
    - debug:
        msg: "Congratulations. Humio is now available at http://{{ hostvars[groups['humios']|random]['ansible_' + humio_network_interface].ipv4.address }}:8080"
