---

- hosts: zookeepers
  become: true
  tags: zookeeper
  roles:
    - role: humio.java
    - role: AnsibleShipyard.ansible-zookeeper
      vars:
         - zookeeper_version: 3.4.14
         - zookeeper_url: https://archive.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz
         - zookeeper_debian_systemd_enabled: true
      zookeeper_hosts: "
            {%- set ips = [] %}
            {%- for host in groups['zookeepers'] %}
            {{- ips.append(dict(id=hostvars[host]['cluster_index'], host=host, ip=hostvars[host].ipv4.address)) }}
            {%- endfor %}
            {{- ips -}}"

- hosts: kafka
  tags: kafka
  become: true
  roles:
    - role: humio.java
    - role: humio.kafka
      kafka_broker_id: "{{ tags.cluster_index }}"
      zookeeper_hosts: "
       {%- set ips = [] %}
       {%- for host in groups['zookeepers'] %}
       {{- ips.append(dict(id=hostvars[host]['tags']['cluster_index'], host=host, ip=hostvars[host]['private_ip_address'])) }}
       {%- endfor %}
       {{- ips -}}"
      kafka_listeners:
        - host: "{{ private_ip_address }}"

- hosts: humio
  tags: humio
  # debugger: always
  become: true
  serial: 1
  roles: 
    - role: humio.java
    - role: humio.server
      humio_host_id: "{{ tags.humio }}"
      zookeeper_hosts: "
        {%- set ips = [] %}
        {%- for host in groups['zookeepers'] %}
        {{- ips.append(dict(id=hostvars[host]['tags']['zookeeper'], host=host, ip=hostvars[host].ipv4.address))  }}
        {%- endfor %}
        {{- ips -}}"
      kafka_hosts: "
        {%- set ips = [] %}
        {%- for host in groups['kafka'] %}
        {{- ips.append(dict(id=hostvars[host]['tags']['kafka'], host=host, ip=hostvars[host].ipv4.address))  }}
        {%- endfor %}
        {{- ips -}}"
      humio_config:
        "all": "humio-config"
        "0": "EXTERNAL_URL=http://{{ private_ip_address }}:8080"