---
- src: https://github.com/elastic/ansible-beats

- src: AnsibleShipyard.ansible-zookeeper
  version: 0.23.0

- src: humio.kafka
  version: 0.1.5

- src: humio.server
  version: 0.3.2

- src: geerlingguy.firewall
  version: 2.4.1
