zookeeper_version: 3.4.13
zookeeper_url: "http://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
zookeeper_host: localhost
zookeeper_port: 2181
zookeeper_id: 1

kafka_log_dirs: "/var/humio/kafka/data"

output_conf:
  "elasticsearch":
    "hosts": ["{{ lookup('env', 'HUMIO_PARENT_URL') }}"]
    "username": "{{ lookup('env', 'HUMIO_PARENT_INGEST_TOKEN') }}"

beats_version: 6.6.0

humio_disks:
  - description: "Humio primary disk"
    disk: "/dev/md/primary"
    destination: "/var/humio/primary"
    type: "xfs"
  - description: "Humio secondary disk"
    disk: "/dev/md/secondary"
    destination: "/var/humio/secondary"
    type: "xfs"

