zookeeper_host: localhost
zookeeper_port: 2181
zookeeper_id: 1

kafka_log_dirs: "/var/humio/kafka/data"

humio_data_path: "/var/humio/server"

output_conf:
  "elasticsearch":
    "hosts": ["{{ lookup('env', 'HUMIO_PARENT_URL') }}"]
    "username": "{{ lookup('env', 'HUMIO_PARENT_INGEST_TOKEN') }}"

beats_version: 6.4.1
